<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="3" failed="5" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-16T16:05:26 CEST" name="Suite" finished-at="2023-04-16T16:05:56 CEST" duration-ms="30514">
    <groups>
    </groups>
    <test started-at="2023-04-16T16:05:26 CEST" name="Test" finished-at="2023-04-16T16:05:56 CEST" duration-ms="30514">
      <class name="com.tests.SomeRandomTest">
        <test-method is-config="true" signature="lanuchApplication()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:26 CEST" name="lanuchApplication" finished-at="2023-04-16T16:05:32 CEST" duration-ms="6095" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanuchApplication -->
        <test-method is-config="true" signature="lanuchApplication()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:26 CEST" name="lanuchApplication" finished-at="2023-04-16T16:05:32 CEST" duration-ms="6097" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanuchApplication -->
        <test-method signature="someTest02()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:32 CEST" name="someTest02" finished-at="2023-04-16T16:05:34 CEST" duration-ms="2425" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.tests.SomeRandomTest.someTest02(SomeRandomTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- someTest02 -->
        <test-method signature="someTest01()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:32 CEST" name="someTest01" finished-at="2023-04-16T16:05:34 CEST" duration-ms="2417" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- someTest01 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:34 CEST" name="tearDown" finished-at="2023-04-16T16:05:34 CEST" duration-ms="87" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lanuchApplication()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:34 CEST" name="lanuchApplication" finished-at="2023-04-16T16:05:39 CEST" duration-ms="4657" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanuchApplication -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:34 CEST" name="tearDown" finished-at="2023-04-16T16:05:34 CEST" duration-ms="84" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lanuchApplication()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:34 CEST" name="lanuchApplication" finished-at="2023-04-16T16:05:39 CEST" duration-ms="4782" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanuchApplication -->
        <test-method signature="someTest03()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:39 CEST" name="someTest03" finished-at="2023-04-16T16:05:41 CEST" duration-ms="2366" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.tests.SomeRandomTest.someTest03(SomeRandomTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- someTest03 -->
        <test-method signature="someTest04()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:39 CEST" name="someTest04" finished-at="2023-04-16T16:05:42 CEST" duration-ms="2363" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.tests.SomeRandomTest.someTest04(SomeRandomTest.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- someTest04 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:41 CEST" name="tearDown" finished-at="2023-04-16T16:05:42 CEST" duration-ms="97" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lanuchApplication()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:42 CEST" name="lanuchApplication" finished-at="2023-04-16T16:05:46 CEST" duration-ms="4214" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanuchApplication -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:42 CEST" name="tearDown" finished-at="2023-04-16T16:05:42 CEST" duration-ms="63" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lanuchApplication()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:42 CEST" name="lanuchApplication" finished-at="2023-04-16T16:05:46 CEST" duration-ms="4704" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanuchApplication -->
        <test-method signature="someTest05()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:46 CEST" name="someTest05" finished-at="2023-04-16T16:05:48 CEST" duration-ms="2356" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- someTest05 -->
        <test-method signature="someTest06()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:46 CEST" name="someTest06" finished-at="2023-04-16T16:05:49 CEST" duration-ms="2333" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.tests.SomeRandomTest.someTest06(SomeRandomTest.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- someTest06 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:48 CEST" name="tearDown" finished-at="2023-04-16T16:05:48 CEST" duration-ms="51" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lanuchApplication()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:48 CEST" name="lanuchApplication" finished-at="2023-04-16T16:05:53 CEST" duration-ms="4633" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanuchApplication -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:49 CEST" name="tearDown" finished-at="2023-04-16T16:05:49 CEST" duration-ms="96" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lanuchApplication()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:49 CEST" name="lanuchApplication" finished-at="2023-04-16T16:05:54 CEST" duration-ms="4586" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanuchApplication -->
        <test-method signature="someTest07()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:53 CEST" name="someTest07" finished-at="2023-04-16T16:05:55 CEST" duration-ms="2320" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- someTest07 -->
        <test-method signature="someTest08()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:54 CEST" name="someTest08" finished-at="2023-04-16T16:05:56 CEST" duration-ms="2325" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.tests.SomeRandomTest.someTest08(SomeRandomTest.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- someTest08 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:55 CEST" name="tearDown" finished-at="2023-04-16T16:05:55 CEST" duration-ms="89" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.SomeRandomTest@31ea9581]" started-at="2023-04-16T16:05:56 CEST" name="tearDown" finished-at="2023-04-16T16:05:56 CEST" duration-ms="61" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tests.SomeRandomTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
